config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'

  resources :cocktails, only: [:show, :index, :create, :new] do
    resources :doses, only: [:create, :new, :destroy]
  end

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient
  validates :amount, :cocktail, :ingredient, presence: true
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :picture)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :get_cocktail

  def new
    @ingredients = Ingredient.all
    @dose = Dose.new(cocktail: @cocktail)
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

private

  def dose_params
    params.require(:dose).permit(:amount, :ingredient_id)
  end

  def get_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @ingredients = Ingredient.all
  end

  def show

  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.create(ingredient_params)
    if @ingredient.save
      redirect_to_ingredient_path(@ingredient)
    else
      render :new
    end
  end

  def edit

  end

  def update
    @ingredient.update(ingredient_params)
    if @ingredient.save
      redirect_to_ingredient_path(@ingredient)
    else
      render :edit
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to_ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<% content_for(:title) do %>
  Miam, les cocktails délicieux!
<% end %>

<h1>List of cocktails</h1>
<% @cocktails.each do |cocktail| %>
  <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
<% end %>
</br>
<%= link_to "Create new cocktail", new_cocktail_path, class: "btn btn-primary" %>

app/views/cocktails/new.html.erb
<h2>Ajouter un nouveau Cocktail</h2>

<%= bootstrap_form_for(@cocktail, html: { multipart: true }) do |f| %>

  <%= f.text_field :name %>
  <p>

    <%= f.file_field :picture %>
  </p>
  <p><%= f.submit class: "btn btn-primary" %></p>
<% end %>

app/views/cocktails/show.html.erb
<h2><%= @cocktail.name %></h2>

<%= image_tag @cocktail.picture.url(:medium) %>

<ul>
  <% @cocktail.doses.each do |dose| %>
    <li><%= "#{dose.amount} #{dose.ingredient.name}" %></li>
  <% end %>
</ul>

<%= link_to 'Ajouter un ingredient', new_cocktail_dose_path(@cocktail), {class: "btn btn-primary"}  %>

<%= link_to 'Revenir à la liste', cocktails_path, {class: "btn btn-primary"}  %>

app/views/cocktails/show.json.erb
show.json.erb

app/views/doses/_form.html.erb
<%= bootstrap_form_for([@cocktail, @dose]) do |f| %>

  <% if @dose.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @dose.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :content%>

  <%= f.submit "Save dose", class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<h2>Ajouter un ingrédient pour <%= link_to @cocktail.name, cocktail_path(@cocktail) %></h2>

<%= simple_form_for(@dose, url: cocktail_doses_path) do |f| %>
  <%= f.input :amount %>
  <%= f.input :ingredient_id, collection: @ingredients %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Restaurant Reviews" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag "application" %>
  </head>
<body>
  <%= render "shared/navbar" %>
  <div class="wrapper">
    <div class="container">
        <div class="row">
          <div class="col-xs-8 col-sm-4 col-md-4 col-lg-4 col black-left">
            <%= yield %>
            <!-- compléter -->
          </div>
        </div>
      </div>
    </div>
    <%#= render "shared/footer" %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <%= image_tag "logo.svg", id: "logo" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "/users/1/messages" do %>
            <i class="fa fa-envelope-o"></i> Messages
          <% end %>
        </li>
        <li class="dropdown">
          <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
            <%= image_tag "http://placehold.it/30x30", id: "profile-pic" %>
            Profile <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to "/users/1" do %>
                <i class="fa fa-user"></i> Profile
              <% end %>
            </li>
            <li>
              <%= link_to "/users/1/flats" do %>
                <i class="fa fa-home"></i> Flats
              <% end %>
            </li>
            <li>
              <%= link_to "/signout" do %>
                <i class="fa fa-sign-out"></i> Sign Out
              <% end %>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to "/cocktails/new", class: "btn btn-primary", id: "nav-btn" do %>
            Publish a cocktail
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>